version: '3.8'
services:
  portainer-ce:
    restart: always
    image: portainer/portainer-ce
    container_name: "portainer-ce"
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  