version: '3.8'
services:
  mysql-db:
    image: mysql
    container_name: db_mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
    networks:
      - dev

  php-my-admin:
    image: phpmyadmin
    container_name: php_my_admin
    restart: always
    depends_on:
      - mysql-db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql-db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: mail_dev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8081:80
    restart: always
    networks:
      - dev

  www:
    build: php
    container_name: web
    ports:
      - "8090:80"
    volumes:
        - ./php/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    restart: always
    networks:
        - dev

networks:
  dev:
volumes:
  db_data:
     