---
- name: Install nginx
  Become: yes   # Use owner root
  apt: name=nginx state=latest

- name: Start nginx
  Become: yes
  service: name=nginx state=started enabled=true

- name: Delete default conf nginx
  Become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: Reload nginx    # If there are error, use this command inside the server: touch default

- name: Sites configurations
  Become: yes
  include: site.yml
  with_items: domains
