apiVersion: v1
kind: Service
metadata:
  name: svc-service
spec:
  type: NodePort
  selector:
    app: nginx
    env: prod
  ports:
  - nodePort: 31000
    protocol: TCP
    port: 80
    targetPort: 80