apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv01
  labels:
    type: local
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  hostPath:
    path: "/data/"
  