apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc01
spec:
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
