apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    run: nginx-sts-app
spec:
  selector:
    run: nginx-sts-app
  ports:
  - port: 80
    name: web
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  serviceName: nginx-headless
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sts-app
  template:
    metadata:
      labels:
        app: nginx-sts-app
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /var/www/
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      #storageClassName: azurefile
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

